---
apiVersion: crd.forgecloud.com/v1
kind: EncryptedSecret
metadata:
  name: example-login
  namespace: default
source: AWS
awsRegion: us-east-2  # must be set for source: AWS
keys:
- username  # secret manager secret named example-login_username
- password  # secret manager secret named example-login_password

---
apiVersion: crd.forgecloud.com/v1
kind: EncryptedSecret
metadata:
  name: example-login
  namespace: other
source: GCP
gcpProjectID: my-gcp-project-1234  # must be set for source: GCP
disableNameSuffixHash: true  # produce k8s secret named example-login instead of something like example-login-ftc849m4ft
keys:
- username  # secret manager secret named example-login_username
- password  # secret manager secret named example-login_password
- something_else  # secret manager secret named example-login_something_else

---
apiVersion: crd.forgecloud.com/v1
kind: EncryptedSecret
metadata:
  name: sslcertificate
  namespace: default
source: GCP
gcpProjectID: my-gcp-project-4567
type: kubernetes.io/tls
keys:
- ca.crt  # secret manager secret named sslcertificate_ca_crt
- tls.crt  # secret manager secret named sslcertificate_tls_crt
- tls.key  # secret manager secret named sslcertificate_tls_key

